# Generated by Django 4.2.4 on 2023-09-03 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('balance', models.DecimalField(decimal_places=3, max_digits=20)),
                ('accountType', models.CharField(max_length=120)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('name', models.CharField(max_length=120)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionType', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=20)),
                ('date', models.CharField(max_length=120)),
                ('recurringEnd', models.CharField(max_length=120)),
                ('recurringPeriod', models.CharField(max_length=120)),
                ('recurringGap', models.IntegerField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='amyFinancesV2Backend.category')),
                ('fromAccount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactionFromAccount', to='amyFinancesV2Backend.account')),
                ('toAccount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactionToAccount', to='amyFinancesV2Backend.account')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=20)),
                ('isin', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=3, max_digits=20)),
                ('link', models.TextField()),
                ('name', models.CharField(max_length=120)),
                ('watchlisted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=20)),
                ('date', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=3, max_digits=20)),
                ('sum', models.DecimalField(decimal_places=3, max_digits=20)),
                ('cost', models.DecimalField(decimal_places=3, max_digits=20)),
                ('orderType', models.CharField(max_length=120)),
                ('fromAccount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderFromAccount', to='amyFinancesV2Backend.account')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='amyFinancesV2Backend.stock')),
                ('toAccount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderToAccount', to='amyFinancesV2Backend.account')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amountBeforeTax', models.DecimalField(decimal_places=3, max_digits=20)),
                ('payDate', models.CharField(max_length=120)),
                ('taxAmount', models.DecimalField(decimal_places=3, max_digits=20)),
                ('exDate', models.CharField(max_length=120)),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='amyFinancesV2Backend.stock')),
                ('toAccount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='amyFinancesV2Backend.account')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
