# Generated by Django 4.2.4 on 2023-08-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('balance', models.DecimalField(decimal_places=3, max_digits=20)),
                ('accountType', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amountBeforeTax', models.DecimalField(decimal_places=3, max_digits=20)),
                ('payDate', models.CharField(max_length=120)),
                ('taxAmount', models.DecimalField(decimal_places=3, max_digits=20)),
                ('exDate', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=20)),
                ('date', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=3, max_digits=20)),
                ('sum', models.DecimalField(decimal_places=3, max_digits=20)),
                ('cost', models.DecimalField(decimal_places=3, max_digits=20)),
                ('orderType', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=20)),
                ('isin', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=3, max_digits=20)),
                ('link', models.TextField()),
                ('name', models.CharField(max_length=120)),
                ('watchlisted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionType', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=20)),
                ('date', models.CharField(max_length=120)),
                ('recurringEnd', models.CharField(max_length=120)),
                ('recurringPeriod', models.CharField(max_length=120)),
                ('recurringGap', models.IntegerField()),
            ],
        ),
    ]
