# Generated by Django 4.2.4 on 2023-09-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amyFinancesV2Backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='recurringEnd',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='recurringGap',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='recurringPeriod',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
